---
# file: vars/main.yml

# php
php_enablerepo: "remi,remi-php56"
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_enable_php_fpm: true
php_packages:
  - php
  - php-fpm
  - php-cli
  - php-pdo
  - php-intl
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-xmlrpc
  - php-xml
  - php-bcmath
  - php-mysqlnd
  - php-soap

# mysql
mysql_packages:
  - mariadb
  - mariadb-server
  - mariadb-libs
  - MySQL-python
  - perl-DBD-MySQL
mysql_daemon: mariadb
mysql_log_error: /var/log/mariadb/mariadb.log
mysql_syslog_tag: mariadb
mysql_pid_file: /var/run/mariadb/mariadb.pid