---
# file: webservers.yml

- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.apache
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.mailhog
    - php
    - httpd